 - name: Install MySQL5.1 Server
   yum: name={{ item }} state=installed
   with_items:
     - mysql
     - mysql-server
     - MySQL-python
   notify:
     - "start and enable mysql on boot"


 - include: settings.yml
