---
# 初期設定

 - name: タイムゾーンをJSTにする
   shell: cp /usr/share/zoneinfo/Japan /etc/localtime
   tags:
    - mysql51
    - mysql55
    - mysql56
    - php53
    - php54
    - php56
    - postgres92
    - postgres94

 - name: タイムゾーンをJSTにするその２
   template:
     src: clock.j2
     dest: /etc/sysconfig/clock
     owner: root
     group: root
     mode: 0644
   tags:
    - mysql51
    - mysql55
    - mysql56
    - php53
    - php54
    - php56
    - postgres92
    - postgres94

 - name: ホスト名設定
   sudo: true
   hostname:
     name: "{{ host_name }}"
   tags:
    - mysql51
    - mysql55
    - mysql56
    - php53
    - php54
    - php56
    - postgres92
    - postgres94
